### PR TITLE
Add instructions to set up Postgres on C9

### PR DESCRIPTION
**Pull request by jonathanpike**
Here's a write up I did for setting up Postgresql on Cloud9.  Hope it's helpful!

### CODE REVIEW

**Comment by kenmazaika** [comment]
The last PR I just merged put the file in a folder called `docs`.  It also included a link on the README.  Right now we don't have a convention, but it would be good to be consistent - thoughts on how we should organize things?

Content of the PR is super useful!

**Comment by jonathanpike** [comment]
I think putting them in the docs folder is a good idea.  Also, I think the README should have an index of all of the tips, along with a link to their author's github page.  I'll update my PR with these changes, if you agree, @kenmazaika.

**Comment by kenmazaika** [comment]
:+1:

**Comment by jonathanpike** [comment]
@kenmazaika -- I've updated my PR so that my article is now in docs and I've updated the README to include the article, too.

**Comment by kenmazaika** [comment]
This is great!  Thanks for contributing it! :+1:

**Pull request merged**
